language: ruby
rvm:
- 2.4.0
before_script:
- rake db:create
- rake db:schema:load
after_script:
- bundle exec codeclimate-test-reporter
env:
  global:
    secure: YeIoukh6jOu3RH8/U75Mf1XQzckZRnfjBBdkxQ2sgI6Wf7jH8Ki/szB+I/mwECVOFH/fZlUAf5jj8HgK+y2XLPFrsMuNwqGXNUjgyfgvz/8sy7WWifeF3etadqIpgb/iv1bhsyLQxqiFV+3k8R02qM1VlOUF8jzCtr5Vj8//8ee26Oj+rn3dLByHQjvvjaKcnJqmqIBjIfVLD6JqMsProUU0bI/xEiG9L9N8LqbzzutMfHdTCe+ZbPC+My17iCRtG85idWW3ubemZ+XFykGSsNgW1Kg71prvbLgI71AXOVRGHGpfIMoea0z4Rza53386YejQPbnA1oNI7sl6BaqcKSPEKRDvdWG4ugyHmFx6Qyb4Nd2uPCZqqz1N4kr1cccLOGz1PP7QujqnYVm4mwSztqlyChuZjQaMhbPH2yDwJ5FOrvMVMtuxQUbuyd8QwYyHNfkZq2E/ubisvAArENDrrN2ttj1S4CS4FNfHF/jmX0AJpGgYwzVUmxIGc2wGZ/xD7ag2auP0Rx4QJjR5XlbZ7NwvLhWwwjerZqLQpOH+OOHc1Z4EfWn4e0O2xAO+SsCE7tQkcqEJGsI+TzgJ2rWzRVupTbf4y7xXFdO+K4jTm59725HwAqoc8minT5IW9TSWoEWJkK+UgU/Qx64gEXCaDmeIpdSO7+boB7CmeK2I4Kg=
